version: '3'

services:
  database:
    image: 'postgres:latest'
    container_name: postgresql-email
    ports:
      - 15432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

networks: 
  postgres-network:
    driver: bridge