@url = http://localhost:3000
@identity_provider = http://localhost:8180

###
GET {{url}}/ping

###
# @name campaign_create
POST  {{url}}/campaigns
Authorization: Bearer {{access_token}}

{
    "name":"Ipiranga te espera!",
    "content": "Test content flamenguista  123 SAPO",
    "emails": ["richardluizv@gmail.com", "lilianecsilva@hotmail.com", "diogobeen@gmail.com"],
    "createdby": "richardluizv@gmail.com"
}

###
@campaign_id = {{campaign_create.response.body.id}}

###
GET {{url}}/campaigns/{{campaign_id}}
Authorization: Bearer {{access_token}}

###
PATCH {{url}}/campaigns/{{campaign_id}}
Authorization: Bearer {{access_token}}

###
DELETE {{url}}/campaigns/{{campaign_id}}
Authorization: Bearer {{access_token}}


### email-api
# @name token 
POST {{identity_provider}}/auth/realms/provider/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=email-api&username=richardluizv@gmail.com&password=12345&grant_type=password

### email_users
# @name token
POST {{identity_provider}}/auth/realms/provider/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=email_users&username=richardluizv@gmail.com&password=12345&grant_type=password

###
@access_token = {{token.response.body.access_token}}
