POST http://localhost:3000/campaigns

{
    "name":"Richard 2",
    "content": "Test content 2",
    "emails": ["richardluizv@gmail.com"],
    "createdby": "richardluizv@gmail.com"
}
###

GET http://localhost:3000/campaigns/clkbm0d7a2ua5t7fataog

### 

DELETE http://localhost:3000/campaigns/clkacuna2ua4pmnshj0g

### 